SELECT DATACC, SUBSTR(HORARIOS,1,5), SUBSTR(HORARIOS,7,5), SUBSTR(HORARIOS,13,5), SUBSTR(HORARIOS,19,5), SUBSTR(HORARIOS,25,5)FROM
(SELECT DISTINCT TRUNC(A.DATACC)DATACC,
FCN_LINHA_COLUNA(' SELECT TRIM(TO_CHAR(TRUNC(B.HORACC/60),''00''))||'':''||TRIM(TO_CHAR((B.HORACC/60-TRUNC(B.HORACC/60))*60,''00''))
  FROM R070ACC B
 WHERE B.DATACC = TO_DATE('''||TO_CHAR(A.DATACC,'DD/MM/YYYY')||''',''DD/MM/YYYY'')
   AND B.TIPCOL ='||A.TIPCOL ||'
   AND B.NUMEMP ='|| A.NUMEMP ||'
   AND B.NUMCAD ='|| A.NUMCAD ||'
   ORDER BY B.HORACC','-') HORARIOS
 
FROM R070ACC A WHERE A.NUMCAD = 5326
AND A.TIPCOL = 1
AND A.NUMEMP = 1
AND A.DATACC >= TRUNC(SYSDATE-30,'MM')
) X;


SELECT TRUNC(DECODE(SINLAN, '+', QTDHOR, '-', -QTDHOR, 0) / 60) AS HORA,
       ((DECODE(SINLAN, '+', QTDHOR, '-', -QTDHOR, 0) / 60) -
       TRUNC(DECODE(SINLAN, '+', QTDHOR, '-', -QTDHOR, 0) / 60)) * 60 AS MINUTO,
       DATLAN
  FROM R011LAN
 WHERE NUMCAD = 5326
   AND NUMEMP = 1
   AND TIPCOL = 1
 ORDER BY DATLAN DESC;


SELECT TRUNC(A.DATAHORA) DATA,
  MIN(SUBSTR(FCN_LINHA_COLUNA('SELECT TO_CHAR(X.DATAHORA,''HH24:MI'') HORA
  FROM SERVCOMNET.COLETA X
  WHERE X.PIS = '''||A.PIS||''''||'
  AND TO_CHAR(X.DATAHORA,''DD/MM/YYYY'') = '''||TO_CHAR( TRUNC(A.DATAHORA),'DD/MM/YYYY')||''''||
  'ORDER BY X.DATAHORA ASC',' | '),3,200)) HORARIOS
FROM (
  SELECT TO_DATE(TO_CHAR(A.DATAHORA,'DD/MM/YYYY HH24:MI'),'DD/MM/YYYY HH24:MI') DATAHORA, A.PIS
  FROM SERVCOMNET.COLETA A, SERVCOMNET.PESSOA B
  WHERE B.MATRICULA = LPAD(5326,20,'0')
  AND A.PIS = B.PIS
  AND A.DATAHORA >= TRUNC(SYSDATE) - 1
  ORDER BY TO_DATE(TO_CHAR(A.DATAHORA,'DD/MM/YYYY HH24:MI'),'DD/MM/YYYY HH24:MI')) A
GROUP BY TRUNC(A.DATAHORA);

SELECT TRUNC(SUM(DECODE(SINLAN, '+', QTDHOR, '-', -QTDHOR, 0)) / 60) AS HORA,
       ((SUM(DECODE(SINLAN, '+', QTDHOR, '-', -QTDHOR, 0)) / 60) -
       TRUNC(SUM(DECODE(SINLAN, '+', QTDHOR, '-', -QTDHOR, 0)) / 60)) * 60 AS MINUTO,
       MAX(DATLAN)
  FROM R011LAN
 WHERE NUMCAD = 5326
   AND NUMEMP = 1
   AND TIPCOL = 1;
  
