SELECT * FROM ordem_servico os
WHERE os.num_ordem_servico = 72098
AND os.ano_ordem_servico = 2016;

SELECT * FROM triagem_ordem_servico a
WHERE A.NUM_ORDEM = 830199;

SELECT * FROM PEDIDO_SERVICO A
WHERE A.NUM_TRIAGEM_OS IN (1618955,1619032);

SELECT * FROM COTACAO_PEDIDO_SERVICO A
WHERE A.NUM_PEDIDO_SERVICO = 59762;

SELECT * FROM AUTORIZACAO_ENTREGA_SERVICO A
WHERE A.NUM_COTACAO_SERVICO = 75007; 

SELECT * FROM AGENDA_AUT_ENTREGA_SERVICO A
WHERE A.NUM_AUT_ENTREGA_SERVICO = 60886 FOR UPDATE;
