--cirurgias canceladas
SELECT AC.DTA_CIR_PROPOSTA,
       AC.COD_PACIENTE,
       P.NOM_PACIENTE || ' ' || P.SBN_PACIENTE PACIENTE,
       E.NOM_ESPECIALIDADE_HC ESPECIALIDADE,
       U.NOM_USUARIO || ' ' || U.SBN_USUARIO USUARIO,
       AC.DTA_HOR_SUSPENSA,
       M.DSC_MOTIVO
  FROM AGENDA_CIRURGIA  AC,
       MOTIVO           M,
       PACIENTE         P,
       ESPECIALIDADE_HC E,
       USUARIO          U
 WHERE AC.NUM_SEQ_CC = 4440
   AND TRUNC(AC.DTA_CIR_PROPOSTA) >= TO_DATE('18/11/2016', 'DD/MM/YYYY')
   AND AC.IDF_STATUS_CIRURGIA = 1
   AND AC.COD_MOTIVO_SUSPENSAO = M.COD_MOTIVO
   AND AC.COD_PACIENTE = P.COD_PACIENTE
   AND AC.COD_ESPECIALIDADE_HC = E.COD_ESPECIALIDADE_HC
   AND AC.NUM_USER_SUSPENDEU = U.NUM_USER_BANCO
