SELECT * FROM MATERIAL M WHERE M.COD_MATERIAL IN ('77707047', '77704253');


SELECT *
  FROM REQUISICAO_MATERIAL RM       
 WHERE RM.COD_CENCUSTO_ATENDENTE = 'CFCC02010'
   AND RM.COD_CENCUSTO_SOLICITANTE = 'CACD02010'
   AND RM.ANO_REQUISICAO_MATERIAL IN (2016, 2017);

/*Dispensação de Materiais*/
SELECT T.*
  FROM REQUISICAO_MATERIAL RM
       INNER JOIN ESTOQUE.ITEM_REQUISICAO_MATERIAL T
       ON RM.NUM_REQUISICAO = T.NUM_REQUISICAO
 WHERE RM.COD_CENCUSTO_ATENDENTE = 'CFCC02010'
   AND RM.COD_CENCUSTO_SOLICITANTE = 'CADA00026'
   AND RM.ANO_REQUISICAO_MATERIAL = 2017
   AND T.COD_MATERIAL IN ('77707047', '77704253')
   ORDER BY rm.dta_requisicao DESC; --ultima requisição
 
 
SELECT *
  FROM ITEM_REQUISICAO_MATERIAL IRM
 WHERE IRM.COD_MATERIAL = '77707047'
   AND IRM.ANO_REQUISICAO_MATERIAL = 2017
 ORDER BY 1 DESC;



--CADA00026 - ORGANIZAÇÃO 
SELECT * FROM CENTRO_CUSTO CC
WHERE CC.COD_CENCUSTO IN ('CFCC02010', 'CADA00026', 'AAAA00017');



--****Ver estoque em cc secundário 
SELECT M.COD_MATERIAL||' - '||M.NOM_MATERIAL MATERIAL,       
       CC.COD_CENCUSTO||' - '||CC.NOM_CENCUSTO CENTRO_CUSTO,
       EM.QTD_ESTOQUE_MINIMO,
       EM.QTD_ESTOQUE,
       EM.QTD_ESTOQUE_MAXIMO,
       EM.QTD_PROVISORIA,
       EM.QTD_ESTOQUE_CRITICO,
       EM.DTA_ULT_SAIDA       
  FROM ESTOQUE_MATERIAL EM
       INNER JOIN CENTRO_CUSTO CC    
    ON CC.COD_CENCUSTO = EM.COD_CENCUSTO
       INNER JOIN MATERIAL M
    ON M.COD_MATERIAL = EM.COD_MATERIAL
 WHERE 1 = 1
   AND EM.COD_CENCUSTO = 'CFCC02010'
   AND EM.COD_MATERIAL IN ('77707047', '77704253')
   ORDER BY 1 DESC;
   
--ESTOQUE_OPO
--cod_sist: 21
--desc: Consultar saldo materiais de alto custo: 77707047_SOLUCAO DE EURO COLLINS FRASCO 1000 ML, 77704253_SOLUÇÃO PARA CONSERVAÇÃO DE ÓRGÃOS PARA TRANSPLANTE E CARDIOPLEGIA

SELECT * FROM PESQUISA_SISTEMA P ORDER BY 1 DESC

SELECT * FROM PARAMETRO_PESQUISA_SISTEMA P
WHERE P.COD_PESQUISA = 1210;

SELECT P.*, ROWID FROM PESQUISA_SISTEMA P WHERE UPPER(P.NOM_PESQUISA) LIKE  'REQUISIÇÕES POR CENTRO DE CUSTO ATENDENTE E PERÍODO%';

SELECT P.*, ROWID FROM PARAMETRO_PESQUISA_SISTEMA P WHERE P.COD_PESQUISA = 1210
