SELECT OAES.SEQ_PROVISAO_DOTACAO,
      (SELECT DEOU.VLR_LANCAMENTO
       FROM DOTACAO_ESTR_ORC_UTILIZACAO DEOU
       WHERE DEOU.SEQ_PROVISAO_DOTACAO = OAES.SEQ_PROVISAO_DOTACAO
         AND DEOU.IDF_TIPO_LANCAMENTO = 5) VLR_PROVISAO_UTILIZACAO,
      SUM(OAES.VLR_ONERACAO) VLR_ONERACAO,
      (SELECT DEOU.VLR_LANCAMENTO
       FROM DOTACAO_ESTR_ORC_UTILIZACAO DEOU
       WHERE DEOU.SEQ_PROVISAO_DOTACAO = OAES.SEQ_PROVISAO_DOTACAO
         AND DEOU.IDF_TIPO_LANCAMENTO = 5) - SUM(OAES.VLR_ONERACAO) RESULTADO
         
FROM ONERACAO_AUT_ENTREGA_SERVICO OAES
WHERE OAES.SEQ_PROVISAO_DOTACAO = 982
GROUP BY OAES.SEQ_PROVISAO_DOTACAO;
