SELECT 'RIBEIRÃO PRETO, '||TRIM(TO_CHAR(SYSDATE, 'DD')) || ' DE ' ||
       TRIM(TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE=PORTUGUESE')) ||
       ' DE ' || TRIM(TO_CHAR(SYSDATE, 'YYYY')) data_extenso FROM DUAL;
