SELECT 
   H.CODLOC,
   O.NOMLOC,
   U.NUM_USER_BANCO,
   U.NOM_USUARIO_BANCO,
   F.NOMFUN
FROM R034FUN F
    LEFT JOIN R016ORN O ON O.TABORG = F.TABORG AND O.NUMLOC = F.NUMLOC
    LEFT JOIN R016HIE H ON H.TABORG = F.TABORG AND H.NUMLOC = F.NUMLOC AND SYSDATE BETWEEN H.DATINI AND H.DATFIM
    LEFT JOIN USUARIO U ON U.NUM_DOCUMENTO = LPAD(F.NUMCPF,11,'0')
WHERE      
  F.SITAFA <> 7
  AND F.TIPCOL = 1
  AND H.CODLOC LIKE 'DA.%'
ORDER BY CODLOC;   
