/*Pegar malas ativas*/
SELECT DISTINCT (ML.COD_INSTITUTO),
                MC.SEQ_MALA_CAPTACAO,
                MC.DSC_IDENTIFICACAO,
                MC.IDF_STATUS,
                MC.DTA_HOR_INCLUSAO,
                MC.DTA_HOR_ALTERACAO,
                MC.DTA_HOR_INATIVACAO,
                MC.NUM_USER_INCLUSAO,
                MC.NUM_USER_ALTERACAO,
                ML.NOM_LOCAL,
                MC.NUM_USER_INATIVACAO,
                MC.SEQ_REPOSITORIO,
                MC.NUM_SEQ_LOCAL
  FROM MALA_CAPTACAO MC
 INNER JOIN DOACAO_MALA_CAPTACAO DMC
    ON DMC.SEQ_MALA_CAPTACAO = MC.SEQ_MALA_CAPTACAO
 INNER JOIN LACRE_REPOSITORIO L
    ON MC.SEQ_REPOSITORIO = L.SEQ_REPOSITORIO
 INNER JOIN MAPEAMENTO_LOCAL ML
    ON ML.NUM_SEQ_LOCAL = MC.NUM_SEQ_LOCAL
 WHERE MC.IDF_STATUS = 'S'
   AND MC.NUM_SEQ_LOCAL = 11851;


select * from MALA_CAPTACAO t;

SELECT * FROM DOACAO_MALA_CAPTACAO;

SELECT t.SEQ_LACRE_REPOSITORIO FROM DOACAO_MALA_CAPTACAO t;


SELECT * 
FROM LACRE_REPOSITORIO LR 
WHERE LR.SEQ_REPOSITORIO = 93 
 AND LR.COD_SITUACAO_ATUAL = 174;
 
 
 SELECT * FROM DOACAO_MALA_CAPTACAO;

  
  SELECT MC.SEQ_MALA_CAPTACAO, MC.DSC_IDENTIFICACAO 
FROM MALA_CAPTACAO MC 
INNER JOIN DOACAO_MALA_CAPTACAO DMC ON DMC.SEQ_MALA_CAPTACAO = MC.SEQ_MALA_CAPTACAO 
 WHERE DMC.SEQ_DOACAO_BCO_TECIDOS = 78;
