SELECT *
  FROM DOCUMENTO T
 WHERE T.Cod_Especie = 39;
      
   AND ROWNUM <= 10
 ORDER BY T.DTA_EXPEDICAO DESC;

SELECT R.NOM_ROLE, UR.NUM_USER_BANCO
  FROM USUARIO_ROLE UR, ROLE R
 WHERE UR.COD_ROLE = R.COD_ROLE
   AND UR.NUM_USER_BANCO = 66827
   AND R.NOM_ROLE = 'DOC_COMUNICACOES';

WHERE T.NUM_DOCUMENTO = 148 AND T.ANO_DOCUMENTO = 2011 AND T.COD_INSTITUICAO = 1 AND T.COD_ESPECIE = 1;

SELECT *
  FROM OCORRENCIA_DOCUMENTO O
 WHERE O.NUM_DOCUMENTO = 3814
   AND O.ANO_DOCUMENTO = 2011
   AND O.COD_ESPECIE = 1
   AND O.COD_INSTITUICAO = 1;

SELECT * FROM ESPECIE_DOCUMENTO ORDER BY DSC_ESPECIE;

SELECT COD_ESPECIE, DSC_ESPECIE
  FROM ESPECIE_DOCUMENTO
 ORDER BY DSC_ESPECIE;

SELECT * FROM ALL_TABLES A WHERE A.TABLE_NAME LIKE '%DOCUMENTO%';

SELECT * FROM USUARIO A WHERE A.NOM_USUARIO_BANCO = UPPER('mhruska');

SELECT * FROM LOG_ACESSO A WHERE A.NUM_USER_LOG = 3627 ORDER BY 1 DESC;
