/*MPU de materiais*/
SELECT EPU.COD_MATERIAL,
      M.NOM_MATERIAL,
      0 QTD_PROGRAMADA_ANO,
      U.NOM_ABREVIADO UNIDADE,
      NVL(MIS.COD_UNID_CONSUMO, M.COD_UNIDADE) COD_UNID_CONSUMO,
      MIS.QTD_UNID_CONSUMO,
      0 SALDO,
      NVL(EPU.QTD_ESTOQUE, 0) QTD_ESTOQUE,
      NVL(EPU.QTD_ESTOQUE_MINIMO, 0) QTD_ESTOQUE_MINIMO,
      NVL(EPU.QTD_ESTOQUE_MAXIMO, 0) QTD_ESTOQUE_MAXIMO,
      DECODE(MIS.IDF_TIPO_USO, 0, 'EVENTUAL', 'ROTINEIRO') TIPO
 FROM MATERIAL              M,
      MATERIAL_INST_SISTEMA MIS,
      UNIDADE               U,
      GRUPO                 G,
      ESTOQUE_PRONTO_USO    EPU
WHERE EPU.COD_CENCUSTO = 'CACD02010'
  AND MIS.COD_INST_SISTEMA = 1
  AND MIS.COD_MATERIAL = M.COD_MATERIAL
  AND U.COD_UNIDADE = M.COD_UNIDADE
  AND EPU.COD_MATERIAL = M.COD_MATERIAL
  AND G.COD_GRUPO = M.COD_GRUPO
  AND EPU.COD_MATERIAL NOT IN
      (SELECT PM.COD_MATERIAL
         FROM PROGRAMACAO_MATERIAL PM
        WHERE PM.COD_CENCUSTO = 'CACD02010'
          AND PM.ANO_PROGRAMACAO = 2017);
          
SELECT * FROM ESTOQUE_PRONTO_USO EPU WHERE EPU.COD_CENCUSTO = 'CACD02010' AND EPU.COD_MATERIAL = '70102909' ;



SELECT * FROM ordem_servico a
WHERE A.NUM_ORDEM_SERVICO = 82603
  AND A.ANO_ORDEM_SERVICO = 2016 FOR UPDATE;
