SELECT * FROM ORDEM_SERVICO A
WHERE A.NUM_ORDEM_SERVICO IN (10013)
  AND A.ANO_ORDEM_SERVICO = 2017 FOR UPDATE;
  
SELECT * FROM TIPO_SITUACAO_OS;
  
SELECT * FROM ORDEM_SERVICO A
WHERE A.NUM_ORDEM IN (847997) FOR UPDATE;
  
SELECT * FROM TRIAGEM_ORDEM_SERVICO B
WHERE B.NUM_ORDEM IN (850965) FOR UPDATE;  --

SELECT * FROM APONTAMENTO_ATIVIDADE A
WHERE A.NUM_TRIAGEM_OS = 1640473;

SELECT * FROM HISTORICO_ORDEM_SERVICO B  -- 59083
WHERE B.NUM_ORDEM IN (820431) FOR UPDATE
  AND B.SEQ_HISTORICO_OS IN (2986029) FOR UPDATE;

SELECT * FROM HISTORICO_ORDEM_SERVICO B, USUARIO C
WHERE B.NUM_ORDEM IN (772520)
  AND B.NUM_USER_LOG = C.NUM_USER_BANCO;

SELECT * FROM MOVIM_DOCUMENTO_OS A
WHERE A.NUM_TRIAGEM_OS IN (1607935,1609219);

SELECT * FROM HISTORICO_EMIS_PED_PROV_OS A
WHERE A.NUM_SEQUENCIA_EMISSAO = 

SELECT * FROM TIPO_SITUACAO_OS;

SELECT * FROM TRIAGEM_ORDEM_SERVICO B
WHERE B.NUM_TRIAGEM_OS IN (1606604) FOR UPDATE;

SELECT * FROM LOG_ORDEM_SERVICO A
WHERE A.DSC_CHAVE = '272460';

SELECT * FROM MOVIM_DOCUMENTO_OS A
WHERE A.NUM_TRIAGEM_OS IN (993814);

SELECT * FROM UNIDADE_EXECUTANTE A
WHERE A.COD_UNIDADE_EXECUTANTE_PAI = 3;

SELECT COUNT(*) TOTAL,  A.IDF_ESTAGIO_PEDIDO
FROM PEDIDO_SERVICO A
GROUP BY A.IDF_ESTAGIO_PEDIDO

SELECT * FROM PEDIDO_SERVICO C
WHERE C.NUM_TRIAGEM_OS IN (1645420,1644034) FOR UPDATE;

SELECT * FROM PEDIDO_SERVICO C
WHERE C.NUM_PEDIDO_SERVICO IN (59493) FOR UPDATE;

SELECT * FROM COTACAO_PEDIDO_SERVICO D
WHERE D.NUM_PEDIDO_SERVICO IN (61313) FOR UPDATE;  --282641

SELECT * FROM COTACAO_PEDIDO_SERVICO D
WHERE D.NUM_COTACAO_SERVICO = 74705;

SELECT D.NUM_ORDEM_ORIGEM, E.COD_FORNECEDOR, D.NUM_ORDEM, D.NUM_ORDEM_SERVICO, D.ANO_ORDEM_SERVICO, D.DTA_CRIACAO_OS, A.DTA_HOR_COTACAO, B.DTA_HOR_CADASTRO, C.DTA_HOR_TRIAGEM, C.DTA_HOR_FIM_TRIAGEM
FROM COTACAO_PEDIDO_SERVICO A, PEDIDO_SERVICO B, TRIAGEM_ORDEM_SERVICO C, ORDEM_SERVICO D, FORNECEDOR E
WHERE A.NUM_PEDIDO_SERVICO = B.NUM_PEDIDO_SERVICO
  --AND D.NUM_ORDEM IN (261991,304664,368573,368575,368578,368579,368581,368582,368584,370361,372047,372989,373760,452945,522483)
  AND B.NUM_TRIAGEM_OS = C.NUM_TRIAGEM_OS
  AND C.NUM_ORDEM = D.NUM_ORDEM
  AND D.COD_SITUACAO_OS IN (4,5,6) --concluidas (4,5,6,13) abertas (1,2,3,14)
  AND D.COD_UNIDADE_EXECUTANTE = 6
  AND A.COD_FORNECEDOR = E.COD_FORNECEDOR
  AND D.NUM_ORDEM_ORIGEM IS NOT NULL
--GROUP BY E.COD_FORNECEDOR--, D.NUM_ORDEM, D.NUM_ORDEM_SERVICO, D.ANO_ORDEM_SERVICO, D.DTA_CRIACAO_OS, A.DTA_HOR_COTACAO, B.DTA_HOR_CADASTRO, C.DTA_HOR_TRIAGEM, C.DTA_HOR_FIM_TRIAGEM
ORDER BY 1 ;
  
SELECT * FROM ORDEM_SERVICO A
WHERE A.NUM_ORDEM IN (261991);

SELECT * FROM AGRUPAMENTO_COMPRA A
WHERE A.NUM_AGRUPAMENTO = 272448;

SELECT * FROM AUTORIZACAO_ENTREGA_SERVICO E
WHERE E.NUM_COTACAO_SERVICO in (76856) for update;

SELECT * FROM AUTORIZACAO_ENTREGA_SERVICO E   --AF 20047/2016
WHERE E.NUM_AUTORIZACAO_ENTREGA = 25163
  AND E.ANO_AUTORIZACAO_ENTREGA = 2016 FOR UPDATE

SELECT * FROM AUTORIZACAO_ENTREGA_SERVICO E
WHERE E.NUM_AUT_ENTREGA_SERVICO IN (34089);

SELECT * FROM AUTORIZACAO_ENTREGA_SERVICO F
WHERE F.NUM_AUTORIZACAO_ENTREGA IN (30426)
  AND F.ANO_AUTORIZACAO_ENTREGA = 2016
  AND F.NUM_AUT_ENTREGA_SERVICO IN (56346);

SELECT * FROM AUTORIZACAO_ENTREGA F
WHERE F.NUM_AUTORIZACAO_ENTREGA IN (30426)
  AND F.ANO_AUTORIZACAO_ENTREGA = 2016 FOR UPDATE
  AND F.COD_INSTITUICAO = 2;
  
SELECT * FROM  AGENDA_AUT_ENTREGA_SERVICO G
WHERE G.NUM_AUT_ENTREGA_SERVICO IN (60756)  FOR UPDATE  --  624401
  AND G.DTA_AGENDAMENTO = TO_DATE('11/05/2012 09:45:57','DD/MM/YYYY HH24:MI:SS') --FOR UPDATE;

SELECT * FROM LOG_ORDEM_SERVICO A
WHERE A.NOM_TABELA = 'AGENDA_AUT_ENTREGA_SERVICO'
  AND A.DSC_CHAVE = '47523';
  
SELECT * FROM AGENDA_AUT_ENTREGA_SERVICO H
WHERE H.NUM_DOC_FINANCEIRO IN (603353) FOR UPDATE;

select * from DOCUMENTO_FINANCEIRO H
WHERE H.NUM_DOC_FINANCEIRO IN (649796) FOR UPDATE;

SELECT * FROM DOCUMENTO_FINANCEIRO H
WHERE H.COD_FORNECEDOR = 1449;
  
SELECT * FROM FORNECEDOR F
--WHERE F.NOM_FORNECEDOR LIKE 'CON%'
WHERE F.COD_FORNECEDOR IN(1449);

select * from usuario l
where l.num_user_banco = 53728;

SELECT * FROM USUARIO U
WHERE U.NUM_USER_BANCO = 54672;

select * from  DOC_FINANCEIRO_CLASSIFICACAO H
WHERE H.NUM_DOC_FINANCEIRO IN (602811);

DELETE DOCFIN_HISTORICO_CONTABIL I 
WHERE I.NUM_DOC_FINANCEIRO IN (356676);

SELECT * FROM ONERACAO_AUT_ENTREGA_SERVICO J
WHERE J.NUM_AUT_ENTREGA_SERVICO IN (34089) FOR UPDATE;


/*SELECT * FROM ONERACAO_AUT_ENTREGA_SERVICO J
WHERE J.NUM_AUT_ENTREGA_SERVICO IN (33499,33502,33505,33532,33533);
*/
select * from agrupamento_compra
order by 1 desc
SELECT * FROM LOG_ORDEM_SERVICO A
WHERE A.NOM_TABELA = 'AGENDA_AUT_ENTREGA_SERVICO'
  AND A.DSC_CHAVE IN ('55251','55254','55853','55854') FOR UPDATE;

SELECT * FROM AGENDA_AUT_ENTREGA_SERVICO H
WHERE H.NUM_DOC_FINANCEIRO IN (603353) FOR UPDATE;
/*
Conforme conversamos por telefone, segue o que é necessário executar na ordem de serviço nº 16935/2016.

É necessário excluir o recebimento da nota fiscal nº 1317, no valor de R$ 469,32, da Autorização de fornecimento nº 11009/16, tendo em vista que o valor correto desta nota fiscal é de R$ 469,36 e ela é referente a Autorização de Fornecimento nº 13042/2016.

Atenciosamente,
*/

    INSERT INTO LOG_ORDEM_SERVICO (DTA_HOR_LOG,NUM_USER_LOG,IDF_OPERACAO, NOM_TABELA,NOM_COLUNA,DSC_CHAVE,CTU_ANTERIOR)
    VALUES (SYSDATE, FC_NUM_USER_BANCO,'A','AGENDA_AUT_ENTREGA_SERVICO','NUM_DOC_FINANCEIRO',to_char(58345),TO_CHAR(624401));

    INSERT INTO LOG_ORDEM_SERVICO (DTA_HOR_LOG,NUM_USER_LOG,IDF_OPERACAO, NOM_TABELA,NOM_COLUNA,DSC_CHAVE,CTU_ANTERIOR)
    VALUES (SYSDATE, FC_NUM_USER_BANCO,'A','AGENDA_AUT_ENTREGA_SERVICO','NUM_DOC_FINANCEIRO',to_char(55254),TO_CHAR(603353));

    INSERT INTO LOG_ORDEM_SERVICO (DTA_HOR_LOG,NUM_USER_LOG,IDF_OPERACAO, NOM_TABELA,NOM_COLUNA,DSC_CHAVE,CTU_ANTERIOR)
    VALUES (SYSDATE, FC_NUM_USER_BANCO,'A','AGENDA_AUT_ENTREGA_SERVICO','NUM_DOC_FINANCEIRO',to_char(55853),TO_CHAR(603353));

    INSERT INTO LOG_ORDEM_SERVICO (DTA_HOR_LOG,NUM_USER_LOG,IDF_OPERACAO, NOM_TABELA,NOM_COLUNA,DSC_CHAVE,CTU_ANTERIOR)
    VALUES (SYSDATE, FC_NUM_USER_BANCO,'A','AGENDA_AUT_ENTREGA_SERVICO','NUM_DOC_FINANCEIRO',to_char(55854),TO_CHAR(603353));

SELECT */*A.COD_PESQUISA, A.DTA_CADASTRO, 
       REPLACE(REPLACE(A.NOM_PESQUISA,CHR(10),' '),CHR(13),'') NOM_PESQUISA,
       A.DSC_SOLICITANTE, B.NOM_SISTEMA, A.NOM_PESQUISA DSC_PESQUISA, I.NOM_FANTASIA INSTITUICAO*/
FROM SISTEMA B, PESQUISA_SISTEMA A, INSTITUICAO I
WHERE A.COD_SISTEMA=B.COD_SISTEMA AND A.COD_INST_SISTEMA = I.COD_INSTITUICAO
  AND A.COD_SISTEMA=60


SELECT * FROM ORDEM_SERVICO A
WHERE A.NUM_ORDEM_SERVICO = 63515
  AND A.ANO_ORDEM_SERVICO = 2016 FOR UPDATE;

SELECT * FROM TIPO_SITUACAO_OS A
WHERE A.COD_SITUACAO_OS = 22;

SELECT * FROM HISTORICO_ORDEM_SERVICO B
WHERE B.NUM_ORDEM = 821616-- FOR UPDATE
  AND B.SEQ_HISTORICO_OS = 5150873 ;

SELECT * FROM TRIAGEM_ORDEM_SERVICO B
WHERE B.NUM_ORDEM = 821616; --FOR UPDATE;

DELETE MOVIM_DOCUMENTO_OS D
WHERE D.NUM_TRIAGEM_OS IN (1609219)
  AND D.NUM_MOVIM_DOCUMENTO_OS = 50613;
  
DELETE EMISSAO_PEDIDO_PROVIDENCIA_OS B
WHERE B.NUM_ORDEM = 821616
  AND B.NUM_SEQUENCIA_EMISSAO = 40781;

SELECT * FROM HISTORICO_EMIS_PED_PROV_OS C
WHERE C.NUM_SEQUENCIA_EMISSAO IN (40781);

SELECT * FROM TRANSPORTE_MATERIAL;


LIMPEZA INTERNA DO NOTBOOK   ( MOTIVO ESQUENTANDO )  - PATIMONIO HCRP 90280. OBS : FAVOR NÃO FORMATAR,  CIENTE: SR. JOSE.
