SELECT * FROM GENERICO.SCRIPT_BASE SB  FOR UPDATE


SELECT * FROM GENERICO.PARAMETRO_SCRIPT_BASE SB WHERE SB.SEQ_SCRIPT_BASE IN (8,5) FOR UPDATE


SELECT * FROM GENERICO.GERADOR_RELATORIO GR FOR UPDATE


SELECT * FROM GENERICO.RELATORIO_COLUNA RC WHERE RC.SEQ_RELATORIO =  13 FOR UPDATE


SELECT * FROM GENERICO.PARAMETRO_RELATORIO

SELECT * FROM GENERICO.RELATORIO_CATEGORIA FOR UPDATE

SELECT * FROM GENERICO.RELATORIO_PERMISSAO RL FOR UPDATE



select GENERICO.SEQ_GERADOR_RELATORIO.NEXTVAl from dual
------------- Verificar Filtros em caso de erro ----------
select * from usuario u where u.num_user_banco = 63755 


SELECT LOWER(PR.NOM_PARAMETRO) NOM_PARAMETRO, 
CASE 
WHEN (PR.IDF_TIPO_INFORMACAO = 2 AND Z.IDF_ATUALIZA_PARAMETRO = 1) 
THEN TO_CHAR(SYSDATE, 'DD/MM/YYYY') 
ELSE Z.VLR_PARAMETRO 
END AS VLR_PARAMETRO, 
     PR.IDF_OBRIGATORIO, 
     PR.IDF_TIPO_INFORMACAO, 
     Z.IDF_ATUALIZA_PARAMETRO, 
     PR.IDF_FORMA_EXIBICAO, 
     PR.DSC_QUERY, 
     PR.DSC_PARAMETRO 


FROM 
(SELECT PSB.NOM_PARAMETRO, PSB.DSC_PARAMETRO, PSB.IDF_OBRIGATORIO, PSB.IDF_TIPO_INFORMACAO, PSB.ORD_PARAMETRO, 'S' IDF_VISIVEL_USUARIO , PSB.IDF_FORMA_EXIBICAO, PSB.DSC_QUERY, PSB.DSC_VALOR_PADRAO 
FROM GENERICO.PARAMETRO_SCRIPT_BASE PSB 
WHERE PSB.SEQ_SCRIPT_BASE = (SELECT GR.SEQ_SCRIPT_BASE FROM GENERICO.GERADOR_RELATORIO GR WHERE GR.SEQ_RELATORIO = &SEQ_RELATORIO) 
UNION ALL 
SELECT RP.NOM_PARAMETRO, RP.DSC_PARAMETRO, RP.IDF_OBRIGATORIO, RP.IDF_TIPO_INFORMACAO, RP.ORD_PARAMETRO, RP.IDF_VISIVEL_USUARIO, RP.IDF_FORMA_EXIBICAO, RP.DSC_QUERY, RP.DSC_VALOR_PADRAO 
FROM GENERICO.PARAMETRO_RELATORIO RP WHERE RP.SEQ_RELATORIO = &SEQ_RELATORIO AND RP.IDF_VISIVEL_USUARIO = 'S') PR, 

 (SELECT LP.SEQ_LOG_EXECUCAO_RELATORIO, LP.NOM_PARAMETRO, LP.VLR_PARAMETRO, LP.IDF_ATUALIZA_PARAMETRO FROM GENERICO.LOG_PARAM_EXEC_RELATORIO LP 
 WHERE LP.SEQ_LOG_EXECUCAO_RELATORIO = (SELECT X.SEQ_LOG_EXECUCAO_RELATORIO  
  FROM (SELECT LE.SEQ_LOG_EXECUCAO_RELATORIO 
  FROM GENERICO.LOG_EXECUCAO_RELATORIO LE   
  WHERE LE.SEQ_RELATORIO = &SEQ_RELATORIO
  AND LE.NUM_USER_PESQUISA = FC_NUM_USER_BANCO   
  ORDER BY LE.DTA_HOR_PESQUISA DESC) X   
  WHERE ROWNUM = 1)) Z   
 WHERE PR.IDF_VISIVEL_USUARIO = 'S' 

 AND PR.NOM_PARAMETRO = Z.NOM_PARAMETRO(+) 
 ORDER BY PR.ORD_PARAMETRO ASC 




------------ Verificar o Select Gerado ---------------------------

SELECT 

  'SELECT ' || NVL((SELECT WM_CONCAT(COLUNAS) FROM 
 (SELECT DECODE(DSC_TIPO_CALCULO,NULL, DECODE(IDF_TIPO_COLUNA,1, DSC_NOM_COLUNA  || ' "' || DSC_ALIAS_COLUNA || '" ',2, 'ROUND(' || DSC_NOM_COLUNA  || ',8) "' || DSC_ALIAS_COLUNA || '" ' ) , 
DECODE(DSC_TIPO_CALCULO, 'AVG', 'ROUND(AVG', 'SUM', 'ROUND(SUM', DSC_TIPO_CALCULO, DSC_TIPO_CALCULO)  || '(' || DSC_NOM_COLUNA  || ')' 
|| DECODE(DSC_TIPO_CALCULO, 'AVG', ', 8)', 'SUM', ', 8)', DSC_TIPO_CALCULO, '') || ' "' 
 || DSC_ALIAS_COLUNA || '" ' ) COLUNAS 

 FROM GENERICO.RELATORIO_COLUNA 
 WHERE SEQ_RELATORIO = &SEQ_RELATORIO AND NOT(DSC_TIPO_CALCULO IS  NOT NULL AND IDF_EIXO_GRAFICO IS NOT NULL)
  ORDER BY NUM_ORDEM)),'*')


|| CASE WHEN  
(SELECT COUNT(*) 
FROM GENERICO.RELATORIO_ORDENACAO 
WHERE SEQ_RELATORIO = &SEQ_RELATORIO
AND SEQ_RELATORIO IS NOT NULL) > 0 

THEN 

', ROW_NUMBER() OVER (ORDER BY ' || (SELECT WM_CONCAT(ORD) FROM 
 (SELECT DSC_COLUNA || ' ' || DECODE(IDF_TIPO_ORDENACAO, 2 ,'DESC', 1, 'ASC') ORD 
 FROM GENERICO.RELATORIO_ORDENACAO  
 WHERE SEQ_RELATORIO = &SEQ_RELATORIO
ORDER BY NUM_ORDENACAO  ))  || ') RN '  


END

 || ' FROM (' || 

 (SELECT CTU_SCRIPT_BASE 
 FROM GENERICO.SCRIPT_BASE 
 WHERE SEQ_SCRIPT_BASE = (SELECT SEQ_SCRIPT_BASE 
                            FROM GENERICO.GERADOR_RELATORIO 
                           WHERE SEQ_RELATORIO = &SEQ_RELATORIO)) 

|| CASE WHEN  

(SELECT COUNT(*) 
FROM GENERICO.PARAMETRO_RELATORIO 
WHERE SEQ_RELATORIO = &SEQ_RELATORIO AND IDF_OBRIGATORIO = 1
AND DSC_PARAMETRO IS NOT NULL) > 0 

THEN 

 ') WHERE ' || 

 (SELECT REPLACE(WM_CONCAT(DSC_CONDICAO),',',' AND ') FILTROS 
 FROM GENERICO.PARAMETRO_RELATORIO 
 WHERE SEQ_RELATORIO = &SEQ_RELATORIO
                 )   
                 ELSE
                 TO_CLOB(')')     
END 

|| CASE WHEN  

(SELECT COUNT(*) 
FROM GENERICO.RELATORIO_COLUNA 
WHERE SEQ_RELATORIO = &SEQ_RELATORIO
AND IDF_TIPO_COLUNA = 2) > 0 

THEN 

' GROUP BY ' ||              

 (SELECT WM_CONCAT(DSC_NOM_COLUNA) 
 FROM GENERICO.RELATORIO_COLUNA 
 WHERE SEQ_RELATORIO = &SEQ_RELATORIO
 AND IDF_TIPO_COLUNA = 1) 

END      
FROM DUAL

PROCESSO
LICITACAO
ORCAMENTO
COD_MATERIAL
NOM_MATERIAL
NOM_UNIDADE
TIPO_AQUISICAO
ESTAGIO
VLR_AQ_ANT
VLR_BEC
VLR_REFERENCIAL_MAXIMO
VLR_SIAFISICO
VLR_META
QTD_ORCAMENTOS
VLR_NEGOCIADO
VARIACAO_ULTIMA_AQ
INPC_12_ANT
IPCA_12_ANT
IGPM_12_ANT
FORNECEDOR
DTA_FATURAMENTO
DATA_ENTREGA

Processo
Licitação
Orçamento
Cód. Material
Material
Unidade
Tipo aquisição
Estágio
Vlr. Aq. Anterior
Valor BEC
Vl. Referencial Max
Valor SIAFISICO
Valor Meta
Qtd. Orçamentos
Valor negociado
Variação Ult. Aq.
INPC
IPCA
IGPM
Forncedor
Data Faturamento
Data Recebimento

2
3
4
5
6
7
8
9
10
11
11
12
13
14
15
16
17
18
19
20
21
22
