SELECT DISTINCT S.COD_SISTEMA,
       S.NOM_SISTEMA,
       u.nom_usuario||' '||u.sbn_usuario
  FROM USUARIO_ROLE UR,
       USUARIO U,
       SISTEMA S,
       SISTEMA_PERFIL SP
 WHERE UR.COD_ROLE = SP.COD_ROLE
   AND SP.COD_SISTEMA = S.COD_SISTEMA
   AND UR.NUM_USER_BANCO = U.NUM_USER_BANCO
   AND UR.COD_INST_SISTEMA = 1
   AND UR.NUM_USER_BANCO = 64382;
