 /*Consulta da tela de recepção*/
 SELECT VRA.SEQ_VACINA_RECEPCAO_APLIC,
        VR.DTA_HOR_CADASTRO,
        P.COD_PACIENTE,
        P.NOM_PACIENTE,
        P.SBN_PACIENTE,
        FNC_CALCULA_TEMPO(SYSDATE, P.DTA_NASCIMENTO, 'aammdd') IDADE,
        TV.COD_TIPO_VACINA,
        TV.DSC_TIPO_VACINA,
        P.NOM_CIDADE,
        VRA.SEQ_VACINA_RECEPCAO,
        VRA.IDF_STATUS,
        VRA.DSC_JUSTIFICATIVA,
        TO_CHAR(VRA.DTA_HOR_APLICACAO, 'DD/MM/YYYY') DTA_HOR_APLICACAO
   FROM VACINA_RECEPCAO           VR,
        VACINA_RECEPCAO_APLICACAO VRA,
        PACIENTE                  P,
        TIPO_VACINA               TV
  WHERE VR.SEQ_VACINA_RECEPCAO = VRA.SEQ_VACINA_RECEPCAO
    AND VR.COD_PACIENTE = P.COD_PACIENTE
    AND VRA.COD_TIPO_VACINA = TV.COD_TIPO_VACINA
    AND P.NOM_PACIENTE LIKE '%MARIA APARECIDA SANTANA%'
    AND VR.DTA_HOR_CADASTRO BETWEEN
        TO_DATE('09/01/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
        TO_DATE('16/01/2017 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
    AND VR.NUM_SEQ_LOCAL = 12400
 UNION
 SELECT VRA.SEQ_VACINA_RECEPCAO_APLIC,
        VR.DTA_HOR_CADASTRO,
        TO_CHAR(P.COD_PACIENTE_SEM_REGISTRO_HC) COD_PACIENTE,
        P.NOM_PACIENTE,
        P.SBN_PACIENTE,
        FNC_CALCULA_TEMPO(SYSDATE, P.DTA_NASCIMENTO, 'aammdd') IDADE,
        TV.COD_TIPO_VACINA,
        TV.DSC_TIPO_VACINA,
        LOC.NOM_LOCALIDADE NOM_CIDADE,
        VRA.SEQ_VACINA_RECEPCAO,
        VRA.IDF_STATUS,
        VRA.DSC_JUSTIFICATIVA,
        TO_CHAR(VRA.DTA_HOR_APLICACAO, 'DD/MM/YYYY') DTA_HOR_APLICACAO
   FROM VACINA_RECEPCAO           VR,
        VACINA_RECEPCAO_APLICACAO VRA,
        PACIENTE_SEM_REGISTRO_HC  P,
        TIPO_VACINA               TV,
        LOCALIDADE                LOC
  WHERE VR.SEQ_VACINA_RECEPCAO = VRA.SEQ_VACINA_RECEPCAO
    AND VR.COD_PACIENTE_SEM_REGISTRO_HC = P.COD_PACIENTE_SEM_REGISTRO_HC
    AND VRA.COD_TIPO_VACINA = TV.COD_TIPO_VACINA
    AND LOC.SGL_PAIS = P.SGL_PAIS
    AND LOC.SGL_UF = P.SGL_UF
    AND LOC.COD_LOCALIDADE = P.COD_LOCALIDADE
    AND VR.DTA_HOR_CADASTRO BETWEEN
        TO_DATE('09/01/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
        TO_DATE('16/01/2017 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
    AND VR.NUM_SEQ_LOCAL = 12400
  ORDER BY DTA_HOR_CADASTRO
