SELECT *
  FROM VACINA_RECEPCAO VR
 WHERE TRUNC(VR.DTA_HOR_CADASTRO) = TRUNC(SYSDATE)
 ORDER BY 1 DESC;
 
  SELECT NVL(VR.COD_PACIENTE, VR.COD_PACIENTE_SEM_REGISTRO_HC) COD_PACIENTE,
        COUNT(NVL(VR.COD_PACIENTE, VR.COD_PACIENTE_SEM_REGISTRO_HC)) QTD_APLICADA,
        LISTAGG(TC.DSC_TIPO_VACINA, ',' || CHR(10)) WITHIN GROUP(ORDER BY TC.DSC_TIPO_VACINA)
   FROM VACINA_RECEPCAO VR
   JOIN VACINA_RECEPCAO_APLICACAO VRA
     ON VRA.SEQ_VACINA_RECEPCAO = VR.SEQ_VACINA_RECEPCAO
   JOIN TIPO_VACINA TC
     ON TC.COD_TIPO_VACINA = VRA.COD_TIPO_VACINA
  WHERE TRUNC(VR.DTA_HOR_CADASTRO) = TRUNC(SYSDATE) - 1
  GROUP BY NVL(VR.COD_PACIENTE, VR.COD_PACIENTE_SEM_REGISTRO_HC);
 
--**************************

SELECT *
  FROM VACINA_RECEPCAO_APLICACAO T
  JOIN GENERICO.TIPO_VACINA A
    ON A.COD_TIPO_VACINA = T.COD_TIPO_VACINA
 WHERE T.SEQ_VACINA_RECEPCAO IN
       (SELECT VR.SEQ_VACINA_RECEPCAO
          FROM VACINA_RECEPCAO VR
         WHERE VR.COD_PACIENTE = '1254315G')
   /*AND T.COD_TIPO_VACINA = 11*/;


SELECT *  FROM VACINA_RECEPCAO VR
            WHERE VR.COD_PACIENTE = '1157475J';



SELECT AL.OWNER, AL.NAME, AL.TYPE, AL.NAME, COUNT(*)
  FROM ALL_SOURCE AL
 WHERE

 UPPER(TEXT) LIKE UPPER('%vacina_recepcao%')
 GROUP BY AL.NAME, AL.TYPE, AL.OWNER;
 
 --******************************************
 --CFCA00012 FARMÁCIA - GERENCIAMENTO DE ESTOQUE - Fármacia
 --CACD02022 GERENCIAMENTO ESTOQUE DE IMUNOBIOLÓGICOS estoque secundário.
 --CACD02010 SECAO DE ENFERMAGEM PREVENTIVA não é estoque
 SELECT *
  FROM REQUISICAO_MATERIAL RM   
  WHERE 1 = 1    
-- WHERE RM.COD_CENCUSTO_ATENDENTE = 'CFCC02010'
   AND RM.COD_CENCUSTO_SOLICITANTE = 'CACD02010'
   AND RM.ANO_REQUISICAO_MATERIAL = 2017   
   ORDER BY 1 DESC;
   
SELECT *
  FROM ESTOQUE.ITEM_REQUISICAO_MATERIAL T
 WHERE T.NUM_REQUISICAO = 1192391
   AND T.ANO_REQUISICAO_MATERIAL = 2017;
   
 --**********ver centro custo
 SELECT * FROM centro_custo cc
 WHERE cc.cod_cencusto = 'CFCA00012';
 
 select * from AGENDA.LOCAL t
where t.cod_local = '290';

