SELECT TRUNC(SUM(DECODE(SINLAN, '+', QTDHOR, '-', -QTDHOR, 0)) / 60) AS HORA,
       ((SUM(DECODE(SINLAN, '+', QTDHOR, '-', -QTDHOR, 0)) / 60) -
       TRUNC(SUM(DECODE(SINLAN, '+', QTDHOR, '-', -QTDHOR, 0)) / 60)) * 60 AS MINUTO,
       MAX(DATLAN)
  FROM R011LAN
 WHERE NUMCAD = 6373
   AND NUMEMP = 1
   AND TIPCOL = 1;
