CREATE OR REPLACE TRIGGER TG_BI_CERT_LIB_ACESSO
  BEFORE INSERT ON CERT_LIBERACAO_ACESSO
  FOR EACH ROW
DECLARE
  -- local variables here
BEGIN
  IF :NEW.SEQ_CERT_LIBERACAO_ACESSO IS NULL THEN
    SELECT SEQ_CERT_LIBERACAO_ACESSO.NEXTVAL
      INTO :NEW.SEQ_CERT_LIBERACAO_ACESSO
      FROM DUAL;
  END IF;
END TG_BI_CERT_LIB_ACESSO;
/
